services:
  volumes-backup:
    container_name: restic-volumes-backup
    build:
      dockerfile: volumes.Containerfile
    environment: # Complete env in compose.override.yaml
      - CRON_SCHEDULE=5 0 * * * # backup every day at 00:05
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./scripts/:/scripts/:ro
